apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.fullname" . }}-secret
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ .Values.backend.secretKey | b64enc | quote }}
  dbPassword: {{ .Values.postgresql.auth.password | b64enc | quote }}
  rabbitmqPassword: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  oidcClientSecret: {{ .Values.oidc.clientSecret | b64enc | quote }}
