apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-frontend
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-backend
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-postgres
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-rabbitmq
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-events
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: events
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: events
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: events
