ingress:
  enabled: false
  className: istio
  hosts:
    - metabase.homelab.local
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# database:
#   type: postgres
#   postgres:
#     host: "postgres-host"
#     user: "postgres-user"
#     password: "postgres-password"
#     dbname: "metabase"
