---
apiVersion: v1
kind: Service
metadata:
  name: paralus-postgresql
  namespace: paralus
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: paralus-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paralus-postgresql
  namespace: paralus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paralus-postgresql
  template:
    metadata:
      labels:
        app: paralus-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: paralus
            - name: POSTGRES_PASSWORD
              value: paraluspassword
            - name: POSTGRES_DB
              value: paralus
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paralus-postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paralus-postgresql-pvc
  namespace: paralus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
