---
apiVersion: v1
kind: Service
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gitea-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgresql
  template:
    metadata:
      labels:
        app: gitea-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: gitea
            - name: POSTGRES_PASSWORD
              value: giteapassword
            - name: POSTGRES_DB
              value: gitea
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql-pvc
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
